#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

name=wanled

case "$1" in
start)
	stat_busy "Starting $name daemon"
	busybox start-stop-daemon --start --startas wanled.sh -b -m --pidfile /var/run/wanled.pid \
	&& { add_daemon $name; stat_done; } \
	|| { stat_fail; exit 1; }
	;;
stop)
	stat_busy "Stopping $name daemon"
	busybox start-stop-daemon --stop --pidfile /var/run/wanled.pid\
	&& { rm_daemon $name; stat_done; } \
	|| { stat_fail; exit 1; }
	;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
*)
	echo "usage: $0 {start|stop|restart}"
	;;
esac
exit 0
